"""Create the full schema: programs, rates, bonuses, accounts, ledger, transfers, idempotency.

Tables and constraints were autogenerated from app/db/models.py and reviewed by hand. The
parts autogenerate cannot express are added explicitly at the end of upgrade():
- the btree_gist extension (needed by the no-overlapping-bonuses exclusion constraint);
- append-only triggers on ledger_journals, ledger_entries and transfer_events;
- a deferred constraint trigger that rejects any journal that is unbalanced per program.

Revision ID: 0001
Revises:
Create Date: 2026-09-23 13:33:19.091748+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


APPEND_ONLY_TABLES = ("ledger_journals", "ledger_entries", "transfer_events")

CREATE_APPEND_ONLY_FUNCTION = """
CREATE FUNCTION forbid_append_only_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '% is append-only: % is not allowed', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$;
"""

# Runs at COMMIT (deferred), after all entries of the journal have been inserted. Points of
# different programs are different units, so balance is checked per program.
CREATE_BALANCED_JOURNAL_FUNCTION = """
CREATE FUNCTION check_ledger_journal_balanced() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    unbalanced_program_id bigint;
BEGIN
    SELECT program_id INTO unbalanced_program_id
    FROM ledger_entries
    WHERE journal_id = NEW.journal_id
    GROUP BY program_id
    HAVING SUM(CASE WHEN direction = 'DEBIT' THEN amount ELSE 0 END)
        <> SUM(CASE WHEN direction = 'CREDIT' THEN amount ELSE 0 END)
    LIMIT 1;

    IF FOUND THEN
        RAISE EXCEPTION 'ledger journal % is unbalanced for program %',
            NEW.journal_id, unbalanced_program_id
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$$;
"""


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic (reviewed) ###
    op.create_table('programs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('partner_code', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[A-Z][A-Z0-9_]{1,49}$'", name=op.f('ck_programs_code_format')),
    sa.CheckConstraint("type IN ('CARD', 'LOYALTY')", name=op.f('ck_programs_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs')),
    sa.UniqueConstraint('code', name=op.f('uq_programs_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id ~ '^[A-Za-z0-9_.-]{1,64}$'", name=op.f('ck_users_id_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('external_member_id', sa.String(length=100), nullable=True),
    sa.Column('balance', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(owner_type = 'USER' AND user_id IS NOT NULL AND account_type = 'USER_BALANCE' AND external_member_id IS NOT NULL) OR (owner_type = 'SYSTEM' AND user_id IS NULL AND account_type <> 'USER_BALANCE' AND external_member_id IS NULL)", name=op.f('ck_accounts_owner_consistent')),
    sa.CheckConstraint("account_type IN ('USER_BALANCE', 'TRANSFER_CLEARING', 'PARTNER_SETTLEMENT')", name=op.f('ck_accounts_account_type_valid')),
    sa.CheckConstraint("owner_type <> 'USER' OR balance >= 0", name=op.f('ck_accounts_user_balance_non_negative')),
    sa.CheckConstraint("owner_type IN ('USER', 'SYSTEM')", name=op.f('ck_accounts_owner_type_valid')),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_accounts_program_id_programs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('id', 'program_id', name='uq_accounts_id_program'),
    sa.UniqueConstraint('program_id', 'external_member_id', name='uq_accounts_program_external_member'),
    sa.UniqueConstraint('user_id', 'program_id', name='uq_accounts_user_program')
    )
    op.create_index('uq_accounts_system_program_type', 'accounts', ['program_id', 'account_type'], unique=True, postgresql_where=sa.text("owner_type = 'SYSTEM'"))
    op.create_table('conversion_rates',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source_program_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_program_id', sa.BigInteger(), nullable=False),
    sa.Column('numerator', sa.BigInteger(), nullable=False),
    sa.Column('denominator', sa.BigInteger(), nullable=False),
    sa.Column('min_source_points', sa.BigInteger(), nullable=False),
    sa.Column('source_increment', sa.BigInteger(), nullable=False),
    sa.Column('max_source_points', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('denominator > 0', name=op.f('ck_conversion_rates_denominator_positive')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name=op.f('ck_conversion_rates_effective_window_valid')),
    sa.CheckConstraint('max_source_points IS NULL OR max_source_points >= min_source_points', name=op.f('ck_conversion_rates_max_not_below_min')),
    sa.CheckConstraint('min_source_points >= 1', name=op.f('ck_conversion_rates_min_source_points_positive')),
    sa.CheckConstraint('numerator > 0', name=op.f('ck_conversion_rates_numerator_positive')),
    sa.CheckConstraint('source_increment >= 1', name=op.f('ck_conversion_rates_source_increment_positive')),
    sa.CheckConstraint('source_program_id <> destination_program_id', name=op.f('ck_conversion_rates_distinct_programs')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_conversion_rates_version_positive')),
    sa.ForeignKeyConstraint(['destination_program_id'], ['programs.id'], name=op.f('fk_conversion_rates_destination_program_id_programs')),
    sa.ForeignKeyConstraint(['source_program_id'], ['programs.id'], name=op.f('fk_conversion_rates_source_program_id_programs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversion_rates')),
    sa.UniqueConstraint('source_program_id', 'destination_program_id', 'version', name='uq_conversion_rates_route_version')
    )
    op.create_index('ix_conversion_rates_route_effective', 'conversion_rates', ['source_program_id', 'destination_program_id', 'effective_from'], unique=False)
    op.create_index('uq_conversion_rates_route_open_version', 'conversion_rates', ['source_program_id', 'destination_program_id'], unique=True, postgresql_where=sa.text('effective_to IS NULL AND active'))
    op.create_table('transfer_bonuses',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source_program_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_program_id', sa.BigInteger(), nullable=False),
    sa.Column('bonus_bps', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('source_program_id'), '='), (sa.column('destination_program_id'), '='), (sa.text('tstzrange(starts_at, ends_at)'), '&&'), using='gist', name='ex_transfer_bonuses_no_overlap'),
    sa.CheckConstraint('bonus_bps > 0 AND bonus_bps <= 10000', name=op.f('ck_transfer_bonuses_bonus_bps_range')),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_transfer_bonuses_window_valid')),
    sa.CheckConstraint('source_program_id <> destination_program_id', name=op.f('ck_transfer_bonuses_distinct_programs')),
    sa.ForeignKeyConstraint(['destination_program_id'], ['programs.id'], name=op.f('fk_transfer_bonuses_destination_program_id_programs')),
    sa.ForeignKeyConstraint(['source_program_id'], ['programs.id'], name=op.f('fk_transfer_bonuses_source_program_id_programs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_bonuses'))
    )
    op.create_table('transfers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('source_program_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_program_id', sa.BigInteger(), nullable=False),
    sa.Column('source_account_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_account_id', sa.BigInteger(), nullable=False),
    sa.Column('source_points', sa.BigInteger(), nullable=False),
    sa.Column('base_points', sa.BigInteger(), nullable=False),
    sa.Column('bonus_points', sa.BigInteger(), nullable=False),
    sa.Column('destination_points', sa.BigInteger(), nullable=False),
    sa.Column('rate_id', sa.BigInteger(), nullable=False),
    sa.Column('rate_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.String(length=500), nullable=True),
    sa.Column('partner_reference', sa.String(length=64), nullable=True),
    sa.Column('partner_confirmation_id', sa.String(length=128), nullable=True),
    sa.Column('verification_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_verification_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status IN ('COMPLETED', 'REVERSED')) = (completed_at IS NOT NULL)", name=op.f('ck_transfers_final_has_completed_at')),
    sa.CheckConstraint("id ~ '^tr_[0-9A-HJKMNP-TV-Z]{26}$'", name=op.f('ck_transfers_id_format')),
    sa.CheckConstraint("status <> 'COMPLETED' OR partner_confirmation_id IS NOT NULL", name=op.f('ck_transfers_completed_has_confirmation')),
    sa.CheckConstraint("status <> 'REVERSED' OR failure_code IS NOT NULL", name=op.f('ck_transfers_reversed_has_failure_code')),
    sa.CheckConstraint("status IN ('PENDING', 'SOURCE_DEBITED', 'PARTNER_SUBMITTED', 'PENDING_VERIFICATION', 'COMPLETED', 'REVERSED', 'MANUAL_REVIEW')", name=op.f('ck_transfers_status_valid')),
    sa.CheckConstraint('base_points >= 0', name=op.f('ck_transfers_base_points_non_negative')),
    sa.CheckConstraint('bonus_points >= 0', name=op.f('ck_transfers_bonus_points_non_negative')),
    sa.CheckConstraint('destination_points = base_points + bonus_points', name=op.f('ck_transfers_destination_points_sum')),
    sa.CheckConstraint('destination_points > 0', name=op.f('ck_transfers_destination_points_positive')),
    sa.CheckConstraint('source_points > 0', name=op.f('ck_transfers_source_points_positive')),
    sa.CheckConstraint('source_program_id <> destination_program_id', name=op.f('ck_transfers_distinct_programs')),
    sa.CheckConstraint('verification_attempts >= 0', name=op.f('ck_transfers_verification_attempts_non_negative')),
    sa.ForeignKeyConstraint(['destination_account_id', 'destination_program_id'], ['accounts.id', 'accounts.program_id'], name='fk_transfers_destination_account_program'),
    sa.ForeignKeyConstraint(['destination_program_id'], ['programs.id'], name=op.f('fk_transfers_destination_program_id_programs')),
    sa.ForeignKeyConstraint(['rate_id'], ['conversion_rates.id'], name=op.f('fk_transfers_rate_id_conversion_rates')),
    sa.ForeignKeyConstraint(['source_account_id', 'source_program_id'], ['accounts.id', 'accounts.program_id'], name='fk_transfers_source_account_program'),
    sa.ForeignKeyConstraint(['source_program_id'], ['programs.id'], name=op.f('fk_transfers_source_program_id_programs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transfers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfers')),
    sa.UniqueConstraint('partner_reference', name=op.f('uq_transfers_partner_reference')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_transfers_user_idempotency_key')
    )
    op.create_index('ix_transfers_reconcilable', 'transfers', ['status', 'next_verification_at'], unique=False, postgresql_where=sa.text("status IN ('SOURCE_DEBITED', 'PARTNER_SUBMITTED', 'PENDING_VERIFICATION')"))
    op.create_index('ix_transfers_user_created', 'transfers', ['user_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transfer_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("request_fingerprint ~ '^[0-9a-f]{64}$'", name=op.f('ck_idempotency_keys_fingerprint_format')),
    sa.CheckConstraint("status <> 'COMPLETED' OR response_status_code IS NOT NULL", name=op.f('ck_idempotency_keys_completed_has_response')),
    sa.CheckConstraint("status IN ('IN_PROGRESS', 'COMPLETED')", name=op.f('ck_idempotency_keys_status_valid')),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_idempotency_keys_expiry_after_creation')),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], name=op.f('fk_idempotency_keys_transfer_id_transfers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idempotency_keys_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('user_id', 'key', name='uq_idempotency_keys_user_key')
    )
    op.create_index(op.f('ix_idempotency_keys_expires_at'), 'idempotency_keys', ['expires_at'], unique=False)
    op.create_table('ledger_journals',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('journal_type', sa.String(length=32), nullable=False),
    sa.Column('transfer_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(journal_type = 'SEED') = (transfer_id IS NULL)", name=op.f('ck_ledger_journals_transfer_link_consistent')),
    sa.CheckConstraint("journal_type IN ('SEED', 'TRANSFER_DEBIT', 'TRANSFER_SETTLE', 'TRANSFER_REVERSAL')", name=op.f('ck_ledger_journals_journal_type_valid')),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], name=op.f('fk_ledger_journals_transfer_id_transfers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_journals')),
    sa.UniqueConstraint('transfer_id', 'journal_type', name='uq_ledger_journals_transfer_type')
    )
    op.create_table('transfer_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('transfer_id', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("from_status IS NULL OR from_status IN ('PENDING', 'SOURCE_DEBITED', 'PARTNER_SUBMITTED', 'PENDING_VERIFICATION', 'COMPLETED', 'REVERSED', 'MANUAL_REVIEW')", name=op.f('ck_transfer_events_from_status_valid')),
    sa.CheckConstraint("to_status IN ('PENDING', 'SOURCE_DEBITED', 'PARTNER_SUBMITTED', 'PENDING_VERIFICATION', 'COMPLETED', 'REVERSED', 'MANUAL_REVIEW')", name=op.f('ck_transfer_events_to_status_valid')),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], name=op.f('fk_transfer_events_transfer_id_transfers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_events'))
    )
    op.create_index('ix_transfer_events_transfer_id_id', 'transfer_events', ['transfer_id', 'id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('journal_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('DEBIT', 'CREDIT')", name=op.f('ck_ledger_entries_direction_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_ledger_entries_amount_positive')),
    sa.ForeignKeyConstraint(['account_id', 'program_id'], ['accounts.id', 'accounts.program_id'], name='fk_ledger_entries_account_program'),
    sa.ForeignKeyConstraint(['journal_id'], ['ledger_journals.id'], name=op.f('fk_ledger_entries_journal_id_ledger_journals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    op.create_index(op.f('ix_ledger_entries_account_id'), 'ledger_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_journal_id'), 'ledger_entries', ['journal_id'], unique=False)
    # ### end Alembic commands ###

    op.execute(CREATE_APPEND_ONLY_FUNCTION)
    for table in APPEND_ONLY_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_append_only_mutation()"
        )

    op.execute(CREATE_BALANCED_JOURNAL_FUNCTION)
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_ledger_entries_journal_balanced "
        "AFTER INSERT ON ledger_entries DEFERRABLE INITIALLY DEFERRED "
        "FOR EACH ROW EXECUTE FUNCTION check_ledger_journal_balanced()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_ledger_entries_journal_balanced ON ledger_entries")
    op.execute("DROP FUNCTION IF EXISTS check_ledger_journal_balanced()")
    for table in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS forbid_append_only_mutation()")
    # btree_gist is left installed: other schemas may use it and it holds no data.

    # ### commands auto generated by Alembic (reviewed) ###
    op.drop_index(op.f('ix_ledger_entries_journal_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_account_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_transfer_events_transfer_id_id', table_name='transfer_events')
    op.drop_table('transfer_events')
    op.drop_table('ledger_journals')
    op.drop_index(op.f('ix_idempotency_keys_expires_at'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_transfers_user_created', table_name='transfers')
    op.drop_index('ix_transfers_reconcilable', table_name='transfers', postgresql_where=sa.text("status IN ('SOURCE_DEBITED', 'PARTNER_SUBMITTED', 'PENDING_VERIFICATION')"))
    op.drop_table('transfers')
    op.drop_table('transfer_bonuses')
    op.drop_index('uq_conversion_rates_route_open_version', table_name='conversion_rates', postgresql_where=sa.text('effective_to IS NULL AND active'))
    op.drop_index('ix_conversion_rates_route_effective', table_name='conversion_rates')
    op.drop_table('conversion_rates')
    op.drop_index('uq_accounts_system_program_type', table_name='accounts', postgresql_where=sa.text("owner_type = 'SYSTEM'"))
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('programs')
    # ### end Alembic commands ###
